title: 'caosOrdenado'
description: 'Blog do estrategista de conteúdo e designer Eduardo Fernandes'
url: 'http://caosordenado.com'
author: Eduardo Fernandes
timezone: America/Sao_Paulo
email: '&#x65;&#x64;&#x75;&#x66;&#x37;&#x35;&#x40;&#x67;&#x6D;&#x61;&#x69;&#x6C;&#x2E;&#x63;&#x6F;&#x6D;'

highlighter: pygments
lsi: false
markdown: kramdown
permalink: /:title
paginate: 12
future: true

kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6

twitter: http://twitter.com/eduf
facebook: https://www.facebook.com/edufcaosordenado
plus: https://plus.google.com/118332442513569100227
newsletter: http://eepurl.com/UYTxf
