site_name: 'Caos Ordenado'
site_url: 'http://www.caosordenado.com'
timezone: America/Sao_Paulo
pygments: true
lsi: false
markdown: kramdown
permalink: /:title
paginate: 12
future:      true

kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6