site_name: 'Caos Ordenado'
site_url: 'http://caosordenado.com'
timezone: America/Sao_Paulo
highlighter: pygments
lsi: false
markdown: kramdown
permalink: /:title
paginate: 12
future:      true

kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
